#pragma once
#pragma warning(disable:4996)
#include <string>
#include <vector>
#include <array>
#include <future>
#include <optional>
#include <filesystem>
#include <iostream>
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <Windows.h>
#include <spdlog/spdlog.h>
#include <d3d12.h>
#include "SimpleMath.h"
#include "graphics_common.h"
#include <entt/entt.hpp>                                        
#include <gsl/gsl>
#include <Keyboard.h>
#include <Mouse.h>
#include "fbxsdk/include/fbxsdk.h"
#include "utility.h"
#include <span>
#include "logger.h"
#include <algorithm>
